/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example
import org.example.clases.Persona
import org.example.clases.Fecha
import org.example.clases.Polinomio
import org.example.clases.Cuadratica
import org.example.clases.CuadraticaMejor
import org.example.clases.Cuatrinomio
fun main() {
    println(Persona("pepe", "honguito", Fecha(5, 6, 2026)))
    val polinomio=Polinomio()
    println(Polinomio())
    val cuadratica=Cuadratica()
    println(Cuadratica())
    val cuadraticamejor=CuadraticaMejor()
    println(CuadraticaMejor())
    var objeto: Polinomio
    objeto=Cuadratica() 
    println(objeto)
    objeto=CuadraticaMejor()
    println(objeto)
    var lista = ArrayList <Polinomio>()

    lista.add(Cuadratica())
    lista.add(Polinomio())
    lista.add(CuadraticaMejor())
    lista.add(Cuatrinomio())
    println("desde acá es la lista")
    for (polinomio in lista){
    println(polinomio)
    }
}