/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example
import org.example.clases.Fecha
import org.example.clases.Persona
fun main() {
    println(Persona("pepe", "honguito", Fecha(5, 6, 2026)))
}