/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example
import org.example.clases.Persona
import org.example.clases.Fecha
import org.example.clases.Polinomio
import org.example.clases.Cuadratica
import org.example.clases.CuadraticaMejor
import org.example.clases.Cuatrinomio
import org.example.clases.Termino
fun main() {
    println(Persona("pepe", "honguito", Fecha(5, 6, 2026)))

    var lista = ArrayList <Polinomio>()

    // lista.add(Cuadratica())
    // lista.add(Polinomio())
    // lista.add(CuadraticaMejor())
    // lista.add(Cuatrinomio())
    // println("desde acá es la lista")
    // for (polinomio in lista){
    // println(polinomio)
    // }

    var t1=Termino(2,3)
    var t2=Termino(3,2)
    var t3=Termino(99,0)
    var pol1=Polinomio(listOf(t1,t2,t3))
    var t4=Termino(1,1)
    var polinomio2=Polinomio(listOf(t1,t2,t4,t3))
    println(pol1)
    println(polinomio2)
}